apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-clone.yaml
  - pytest.yaml
  - npm-publish.yaml
  - sbt-publish.yaml
  - pypi-publish.yaml
  - pipeline.yaml
  - triggers.yaml
